/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 robofinal3.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Robot(props) {
    const { nodes, materials } = useGLTF('./models/robot.glb')

    const onClick = (idElement) => {
        const colorSum =
            materials[idElement].color.g + materials[idElement].color.b

        if (colorSum === 2) {
            materials[idElement].color.g = 0
            materials[idElement].color.b = 0
            materials[idElement].emissive.r = 1
        } else {
            materials[idElement].color.g = 1
            materials[idElement].color.b = 1
            materials[idElement].emissive.r = 0
        }
    }

    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <group
                    position={[29.75, 28.97, 496.19]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.11, 1.02, 0.88]}>
                            <mesh
                                geometry={nodes.mesh_id1328.geometry}
                                material={materials['277']}
                                rotation={[1.57, 0, 0]}
                                scale={1.46}
                                onClick={() => onClick('277')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[70.79, 29.14, 496.7]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.15, 1.06, 0.71]}>
                            <mesh
                                geometry={nodes.mesh_id1354.geometry}
                                material={materials['279']}
                                rotation={[1.57, 0, 0]}
                                scale={1.68}
                                onClick={() => onClick('279')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.24, 29.08, 496.12]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.16, 1.07, 0.84]}>
                            <mesh
                                geometry={nodes.mesh_id1340.geometry}
                                material={materials['281']}
                                rotation={[1.57, 0, 0]}
                                scale={1.5}
                                onClick={() => onClick('281')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.03, 48.55, 496.82]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.76]}>
                            <mesh
                                geometry={nodes.mesh_id1338.geometry}
                                material={materials['283']}
                                rotation={[1.57, 0, 0]}
                                scale={1.42}
                                onClick={() => onClick('283')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.7, 105.34, 496.41]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.86]}>
                            <mesh
                                geometry={nodes.mesh_id1332.geometry}
                                material={materials['285']}
                                rotation={[1.57, 0, 0]}
                                scale={1.66}
                                onClick={() => onClick('285')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.65, 86.51, 497.45]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.17, 1.08, 0.89]}>
                            <mesh
                                geometry={nodes.mesh_id1334.geometry}
                                material={materials['287']}
                                rotation={[1.57, 0, 0]}
                                scale={1.3}
                                onClick={() => onClick('287')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.5, 86.79, 498.51]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.11, 1.02, 0.85]}>
                            <mesh
                                geometry={nodes.mesh_id1322.geometry}
                                material={materials['289']}
                                rotation={[1.57, 0, 0]}
                                scale={1.14}
                                onClick={() => onClick('289')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.67, 163.26, 497.65]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.05, 0.97, 0.53]}>
                            <mesh
                                geometry={nodes.mesh_id1257.geometry}
                                material={materials['291']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.19, 0.9, 1.1]}
                                onClick={() => onClick('291')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[135.79, 163.65, 498.04]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.06, 0.98, 0.55]}>
                            <mesh
                                geometry={nodes.mesh_id1259.geometry}
                                material={materials['293']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.12, 0.89, 1.08]}
                                onClick={() => onClick('293')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.98, 143.2, 497.47]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.98]}>
                            <mesh
                                geometry={nodes.mesh_id1303.geometry}
                                material={materials['295']}
                                rotation={[1.57, 0, 0]}
                                scale={1.14}
                                onClick={() => onClick('295')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[135.84, 143.62, 501.45]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.27]}>
                            <mesh
                                geometry={nodes.mesh_id1305.geometry}
                                material={materials['297']}
                                rotation={[1.57, 0, 0]}
                                scale={1.35}
                                onClick={() => onClick('297')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[134.66, 123.31, 501.45]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.25]}>
                            <mesh
                                geometry={nodes.mesh_id1374.geometry}
                                material={materials['299']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.54, 1.51, 1.51]}
                                onClick={() => onClick('299')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.84, 123.71, 502.85]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.16, 1.03, 0.49]}>
                            <mesh
                                geometry={nodes.mesh_id1368.geometry}
                                material={materials['301']}
                                rotation={[1.57, 0, 0]}
                                scale={1.84}
                                onClick={() => onClick('301')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-48.21, -76.17, 354.65]}
                    rotation={[-Math.PI, -1.55, -3.14]}
                    scale={[1.06, 1, 1]}
                >
                    <mesh
                        geometry={nodes.mesh_id1060.geometry}
                        material={materials['257']}
                        rotation={[0, Math.PI / 2, 0]}
                        scale={[1, 1, 0.95]}
                    />
                </group>
                <group
                    position={[-48.12, -120.48, 355.27]}
                    rotation={[0, 0.22, 0]}
                    scale={[0.89, 0.91, 0.89]}
                >
                    <mesh
                        geometry={nodes.mesh_id1062.geometry}
                        material={materials['259']}
                        rotation={[0, Math.PI / 2, 0]}
                    />
                </group>
                <group
                    position={[-48.51, -148.89, 355.16]}
                    rotation={[0, 0.22, 0]}
                    scale={[1.05, 1, 0.93]}
                >
                    <mesh
                        geometry={nodes.mesh_id1068.geometry}
                        material={materials['261']}
                        rotation={[Math.PI, 1.57, 0]}
                        scale={[1.04, 1, 1]}
                    />
                </group>
                <group
                    position={[175.07, -75.64, 358.9]}
                    rotation={[3.14, -1.55, -3.14]}
                    scale={[1, 1.07, 0.95]}
                >
                    <mesh
                        geometry={nodes.mesh_id1058.geometry}
                        material={materials['263']}
                        rotation={[0, Math.PI / 2, 0]}
                    />
                </group>
                <group
                    position={[174.2, -117.55, 359.3]}
                    rotation={[-0.01, -1.56, 0]}
                    scale={[1, 0.87, 1]}
                >
                    <mesh
                        geometry={nodes.mesh_id1064.geometry}
                        material={materials['265']}
                        rotation={[0, Math.PI / 2, 0]}
                    />
                </group>
                <group
                    position={[174.1, -145.49, 359.87]}
                    rotation={[-0.01, -1.56, 0]}
                >
                    <mesh
                        geometry={nodes.mesh_id1066.geometry}
                        material={materials['267']}
                        rotation={[Math.PI, 1.57, 0]}
                        scale={[0.46, 0.5, 0.5]}
                    />
                </group>
                <group
                    position={[70.92, 163.93, 497.08]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.03, 0.95, 0.52]}>
                            <mesh
                                geometry={nodes.mesh_id1253.geometry}
                                material={materials['303']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.08, 0.97, 1.04]}
                                onClick={() => onClick('303')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.08, 144.46, 496.33]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 1.01]}>
                            <mesh
                                geometry={nodes.mesh_id1299.geometry}
                                material={materials['305']}
                                rotation={[1.57, 0, 0]}
                                scale={1.27}
                                onClick={() => onClick('305')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[91.78, 144, 496.54]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.14, 1.05, 0.88]}>
                            <mesh
                                geometry={nodes.mesh_id1301.geometry}
                                material={materials['307']}
                                rotation={[1.57, 0, 0]}
                                scale={1.21}
                                onClick={() => onClick('307')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[92.27, 85.59, 497.19]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.89]}>
                            <mesh
                                geometry={nodes.mesh_id1360.geometry}
                                material={materials['309']}
                                rotation={[1.57, 0, 0]}
                                scale={1.63}
                                onClick={() => onClick('309')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[92.56, 66.77, 496.54]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.16, 1.07, 1.07]}>
                            <mesh
                                geometry={nodes.mesh_id1362.geometry}
                                material={materials['311']}
                                rotation={[1.57, 0, 0]}
                                scale={1.22}
                                onClick={() => onClick('311')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[92.21, 104.87, 496.93]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.77]}>
                            <mesh
                                geometry={nodes.mesh_id1358.geometry}
                                material={materials['313']}
                                rotation={[1.57, 0, 0]}
                                scale={1.32}
                                onClick={() => onClick('313')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[92.27, 124.01, 496.74]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 1.01]}>
                            <mesh
                                geometry={nodes.mesh_id1356.geometry}
                                material={materials['315']}
                                rotation={[1.57, 0, 0]}
                                scale={1.34}
                                onClick={() => onClick('315')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.36, 85.52, 495.67]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.19, 1.04, 0.89]}>
                        <mesh
                            geometry={nodes.mesh_id1372.geometry}
                            material={materials['271']}
                            rotation={[1.57, 0, 0]}
                            scale={1.78}
                            onClick={() => onClick('271')}
                        />
                    </group>
                </group>
                <group
                    position={[113.55, 105.15, 488.04]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 1.11]}>
                        <group scale={[1.09, 1.01, 0.84]}>
                            <mesh
                                geometry={nodes.mesh_id1370.geometry}
                                material={materials['317']}
                                rotation={[1.57, 0, 0]}
                                scale={2.26}
                                onClick={() => onClick('317')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[62.18, 96.85, 492.83]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <mesh
                        geometry={nodes.mesh_id1190.geometry}
                        material={materials['269']}
                        rotation={[0, -0.02, 0]}
                        scale={[0.91, 0.88, 0.07]}
                    />
                </group>
                <group
                    position={[91.76, 48.07, 494.42]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.09, 0.93]}>
                            <mesh
                                geometry={nodes.mesh_id1364.geometry}
                                material={materials['319']}
                                rotation={[1.57, 0, 0]}
                                scale={1.19}
                                onClick={() => onClick('319')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.78, 86.25, 493.7]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.09, 0.76]}>
                            <mesh
                                geometry={nodes.mesh_id1348.geometry}
                                material={materials['321']}
                                rotation={[1.57, 0, 0]}
                                scale={1.92}
                                onClick={() => onClick('321')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.54, 105.46, 493.9]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.73]}>
                            <mesh
                                geometry={nodes.mesh_id1346.geometry}
                                material={materials['323']}
                                rotation={[1.57, 0, 0]}
                                scale={1.57}
                                onClick={() => onClick('323')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.17, 48.63, 494.31]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.73]}>
                            <mesh
                                geometry={nodes.mesh_id1352.geometry}
                                material={materials['325']}
                                rotation={[1.57, 0, 0]}
                                scale={1.88}
                                onClick={() => onClick('325')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.83, 67.02, 492.87]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.07, 0.91]}>
                            <mesh
                                geometry={nodes.mesh_id1350.geometry}
                                material={materials['327']}
                                rotation={[1.57, 0, 0]}
                                scale={2.09}
                                onClick={() => onClick('327')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[71.59, 124.34, 493.92]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.72]}>
                            <mesh
                                geometry={nodes.mesh_id1344.geometry}
                                material={materials['329']}
                                rotation={[1.57, 0, 0]}
                                scale={1.54}
                                onClick={() => onClick('329')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.13, 67.59, 493.76]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.9]}>
                            <mesh
                                geometry={nodes.mesh_id1336.geometry}
                                material={materials['331']}
                                rotation={[1.57, 0, 0]}
                                scale={1.47}
                                onClick={() => onClick('331')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.77, 48.1, 493.77]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.11, 1.02, 0.81]}>
                            <mesh
                                geometry={nodes.mesh_id1326.geometry}
                                material={materials['333']}
                                rotation={[1.57, 0, 0]}
                                scale={1.45}
                                onClick={() => onClick('333')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.72, 67.5, 493.98]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.17, 1.08, 1.08]}>
                            <mesh
                                geometry={nodes.mesh_id1324.geometry}
                                material={materials['335']}
                                rotation={[1.57, 0, 0]}
                                scale={1.35}
                                onClick={() => onClick('335')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[8.96, 125.4, 493.39]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.19, 1.1, 1.03]}>
                            <mesh
                                geometry={nodes.mesh_id1291.geometry}
                                material={materials['337']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.1, 1.09, 1.04]}
                                onClick={() => onClick('337')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[9.08, 144.83, 496.08]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.13, 1.04, 0.71]}>
                            <mesh
                                geometry={nodes.mesh_id1289.geometry}
                                material={materials['339']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.15, 1, 1.12]}
                                onClick={() => onClick('339')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[9.2, 163.52, 493.87]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.02, 0.67]}>
                            <mesh
                                geometry={nodes.mesh_id1247.geometry}
                                material={materials['341']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.29, 1.13, 1.2]}
                                onClick={() => onClick('341')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.77, 163.6, 495.81]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.12, 1.07, 0.71]}>
                            <mesh
                                geometry={nodes.mesh_id1249.geometry}
                                material={materials['343']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.2, 0.81, 1.12]}
                                onClick={() => onClick('343')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.96, 144.57, 497.88]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.11, 1.02, 0.85]}>
                            <mesh
                                geometry={nodes.mesh_id1295.geometry}
                                material={materials['345']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.59, 1.04, 1.52]}
                                onClick={() => onClick('345')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[91.61, 163.59, 494.61]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.59]}>
                            <mesh
                                geometry={nodes.mesh_id1255.geometry}
                                material={materials['347']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.18, 0.98, 1.14]}
                                onClick={() => onClick('347')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.89, 69.94, 496.33]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.15, 1.06, 1.14]}>
                            <mesh
                                geometry={nodes.mesh_id1277.geometry}
                                material={materials['349']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.36, 0.85, 1.33]}
                                onClick={() => onClick('349')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.72, 107.05, 495.93]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.79]}>
                            <mesh
                                geometry={nodes.mesh_id1273.geometry}
                                material={materials['351']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.35, 0.95, 1.31]}
                                onClick={() => onClick('351')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[8.49, 107.08, 497.78]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.09, 0.86]}>
                            <mesh
                                geometry={nodes.mesh_id1293.geometry}
                                material={materials['353']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.36, 1, 1.28]}
                                onClick={() => onClick('353')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.26, 163.29, 493.46]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.12, 1.03, 0.61]}>
                            <mesh
                                geometry={nodes.mesh_id1251.geometry}
                                material={materials['355']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.03, 0.94, 1.03]}
                                onClick={() => onClick('355')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[50.84, 144.12, 495.14]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.77]}>
                            <mesh
                                geometry={nodes.mesh_id1297.geometry}
                                material={materials['357']}
                                rotation={[1.57, 0, 0]}
                                scale={1.74}
                                onClick={() => onClick('357')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[51.06, 124.63, 489.64]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.08, 0.95]}>
                            <mesh
                                geometry={nodes.mesh_id1330.geometry}
                                material={materials['359']}
                                rotation={[1.57, 0, 0]}
                                scale={2.09}
                                onClick={() => onClick('359')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-12, 163.87, 495.14]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.68]}>
                            <mesh
                                geometry={nodes.mesh_id1245.geometry}
                                material={materials['361']}
                                rotation={[1.57, 0, 0]}
                                scale={[0.98, 0.88, 0.99]}
                                onClick={() => onClick('361')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.11, 50.66, 496.26]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.09, 0.94]}>
                            <mesh
                                geometry={nodes.mesh_id1279.geometry}
                                material={materials['363']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.29, 0.88, 1.32]}
                                onClick={() => onClick('363')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.27, 29.62, 496.7]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.15, 1.06, 1.06]}>
                            <mesh
                                geometry={nodes.mesh_id1281.geometry}
                                material={materials['365']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.36, 0.82, 1.4]}
                                onClick={() => onClick('365')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.88, 145.05, 496.11]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.17, 1.08, 0.92]}>
                            <mesh
                                geometry={nodes.mesh_id1269.geometry}
                                material={materials['367']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.12, 0.88, 1.12]}
                                onClick={() => onClick('367')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.5, 125.68, 496]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.87]}>
                            <mesh
                                geometry={nodes.mesh_id1271.geometry}
                                material={materials['369']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.38, 0.94, 1.35]}
                                onClick={() => onClick('369')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[-11.91, 88.22, 496.45]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.1, 1.01, 0.86]}>
                            <mesh
                                geometry={nodes.mesh_id1275.geometry}
                                material={materials['371']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.33, 0.88, 1.26]}
                                onClick={() => onClick('371')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[29.82, 124.75, 495.7]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.15, 1.06, 0.75]}>
                            <mesh
                                geometry={nodes.mesh_id1307.geometry}
                                material={materials['373']}
                                rotation={[1.57, 0, 0]}
                                scale={1.54}
                                onClick={() => onClick('373')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[28.97, 105.43, 492.86]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.23, 1.08, 1.04]}>
                        <mesh
                            geometry={nodes.mesh_id1320.geometry}
                            material={materials['273']}
                            rotation={[1.57, 0, 0]}
                            scale={1.2}
                            onClick={() => onClick('273')}
                        />
                    </group>
                </group>
                <group
                    position={[8.88, 29.38, 493.99]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.17, 1.08, 0.84]}>
                            <mesh
                                geometry={nodes.mesh_id1315.geometry}
                                material={materials['375']}
                                rotation={[1.57, 0, 0]}
                                scale={[1.47, 1.53, 1.53]}
                                onClick={() => onClick('375')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[134.41, 28.33, 495.61]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.11, 1.03, 1.11]}>
                            <mesh
                                geometry={nodes.mesh_id1390.geometry}
                                material={materials['377']}
                                rotation={[1.57, 0, 0]}
                                scale={1.6}
                                onClick={() => onClick('377')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[8.98, 49.32, 495.37]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.14, 1.05, 0.81]}>
                            <mesh
                                geometry={nodes.mesh_id1313.geometry}
                                material={materials['379']}
                                rotation={[1.57, 0, 0]}
                                scale={1.39}
                                onClick={() => onClick('379')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.5, 66.04, 495.79]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.19, 1.05, 0.8]}>
                        <mesh
                            geometry={nodes.mesh_id1380.geometry}
                            material={materials['275']}
                            rotation={[1.57, 0, 0]}
                            scale={2.13}
                            onClick={() => onClick('275')}
                        />
                    </group>
                </group>
                <group
                    position={[134.69, 84.99, 494.74]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.74]}>
                            <mesh
                                geometry={nodes.mesh_id1378.geometry}
                                material={materials['381']}
                                rotation={[1.57, 0, 0]}
                                scale={1.68}
                                onClick={() => onClick('381')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[134, 104.76, 497.46]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.8]}>
                            <mesh
                                geometry={nodes.mesh_id1376.geometry}
                                material={materials['383']}
                                rotation={[1.57, 0, 0]}
                                scale={1.74}
                                onClick={() => onClick('383')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[92.41, 29.31, 494.7]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.17, 1.04, 1.04]}>
                            <mesh
                                geometry={nodes.mesh_id1366.geometry}
                                material={materials['385']}
                                rotation={[1.57, 0, 0]}
                                scale={1.49}
                                onClick={() => onClick('385')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[134.99, 47.37, 495.12]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.61]}>
                            <mesh
                                geometry={nodes.mesh_id1388.geometry}
                                material={materials['387']}
                                rotation={[1.57, 0, 0]}
                                scale={2.27}
                                onClick={() => onClick('387')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[134.94, 66.54, 494.8]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.09, 1.01, 0.65]}>
                            <mesh
                                geometry={nodes.mesh_id1386.geometry}
                                material={materials['389']}
                                rotation={[1.57, 0, 0]}
                                scale={2.09}
                                onClick={() => onClick('389')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.27, 28.96, 495.17]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.12, 1.03, 1.03]}>
                            <mesh
                                geometry={nodes.mesh_id1384.geometry}
                                material={materials['391']}
                                rotation={[1.57, 0, 0]}
                                scale={1.67}
                                onClick={() => onClick('391')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[113.83, 47.64, 494.44]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.15, 1.01, 0.66]}>
                            <mesh
                                geometry={nodes.mesh_id1382.geometry}
                                material={materials['393']}
                                rotation={[1.57, 0, 0]}
                                scale={2.07}
                                onClick={() => onClick('393')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[8.38, 88.22, 494.94]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.23, 1.14, 1.03]}>
                            <mesh
                                geometry={nodes.mesh_id1309.geometry}
                                material={materials['395']}
                                rotation={[1.57, 0, 0]}
                                scale={1.24}
                                onClick={() => onClick('395')}
                            />
                        </group>
                    </group>
                </group>
                <group
                    position={[8.49, 69.33, 496.81]}
                    scale={[1.02, 1.09, 1.02]}
                >
                    <group rotation={[0, -0.02, 0]} scale={[1.04, 0.99, 0.99]}>
                        <group scale={[1.18, 1.09, 0.94]}>
                            <mesh
                                geometry={nodes.mesh_id1311.geometry}
                                material={materials['397']}
                                rotation={[1.57, 0, 0]}
                                scale={1.36}
                                onClick={() => onClick('397')}
                            />
                        </group>
                    </group>
                </group>
                <mesh
                    geometry={nodes.mesh_id1081.geometry}
                    material={materials['237']}
                    position={[235.53, 112.75, 367.35]}
                    rotation={[0, -0.02, 0]}
                    scale={[1.24, 1, 2.35]}
                />
                <mesh
                    geometry={nodes.mesh_id1083.geometry}
                    material={materials['239']}
                    position={[253.41, 111.37, 366.91]}
                    rotation={[0, -0.02, 0]}
                    scale={[1, 1.27, 2.87]}
                />
                <mesh
                    geometry={nodes.mesh_id1085.geometry}
                    material={materials['241']}
                    position={[264.72, 141.01, 367.05]}
                    rotation={[0, -0.02, 0]}
                />
                <mesh
                    geometry={nodes.mesh_id1073.geometry}
                    material={materials['243']}
                    position={[20.58, -194.81, 364.47]}
                    rotation={[0, -0.02, 0]}
                    scale={[1.77, 0.76, 1.69]}
                />
                <mesh
                    geometry={nodes.mesh_id1077.geometry}
                    material={materials['245']}
                    position={[20.73, -223, 363.12]}
                    rotation={[0, -0.02, 0]}
                    scale={[0.98, 1, 0.97]}
                />
                <mesh
                    geometry={nodes.mesh_id1075.geometry}
                    material={materials['247']}
                    position={[104.27, -195.55, 363.76]}
                    rotation={[0, -0.02, 0]}
                    scale={[1, 0.81, 1]}
                />
                <mesh
                    geometry={nodes.mesh_id1079.geometry}
                    material={materials['249']}
                    position={[104.25, -224.48, 365.76]}
                    rotation={[0, -0.02, 0]}
                    scale={[1.14, 1.05, 1.14]}
                />
                <mesh
                    geometry={nodes.mesh_id1056.geometry}
                    material={materials['251']}
                    position={[63.31, -101.87, 364.3]}
                    rotation={[0, -0.02, 0]}
                />
                <mesh
                    geometry={nodes.mesh_id1087.geometry}
                    material={materials['253']}
                    position={[-106.8, 112.54, 357.77]}
                    rotation={[0, -0.02, 0]}
                    scale={[1, 1, 2.39]}
                />
                <mesh
                    geometry={nodes.mesh_id1054.geometry}
                    material={materials['255']}
                    position={[63.1, 97.42, 365.68]}
                    rotation={[0, -0.02, 0]}
                    scale={[0.96, 1.04, 1]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('./models/robot.glb')
